---
title: "Quantifying loss of coral_Remote sensing"
author: "Kai Kopecky"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(car)
```

### Changes in live and dead coral (all plots)

```{r Data cleaning}

# Read in raw data
resilience_plots_raw <- read_csv("Data/Resilience plots_master.csv") 

# Clean up column names, create columns for plot number and time point, and rename coral classes
resilience_plots <- resilience_plots_raw %>% 
  clean_names() %>% 
  mutate(plot = case_when(image_name == "2018-Plot16_PL51_ortho_0.666_matchedColor.jpg" ~ 'Plot 16',
                          image_name == "2019-Plot16_PL52_ortho_0.666.jpg" ~ 'Plot 16',
                          image_name == "2018-Plot17_PL51_ortho_0.666_matchedColor.jpg" ~ 'Plot 17',
                          image_name == "2019-Plot17_PL52_ortho_0.666.jpg" ~ 'Plot 17',
                          image_name == "Plot18_2018_extended.png" ~ 'Plot 18',
                          image_name == "Plot18_2019_extended.png" ~ 'Plot 18',
                          image_name == "2018-Plot19_PL51_ortho_0.666.jpg" ~ 'Plot 19',
                          image_name == "2018-Plot19_PL51_ortho_0.666.jpg" ~ 'Plot 19',
                          image_name == "2019-Plot19_PL51_ortho_0.666.jpg" ~ 'Plot 19',
                          TRUE ~ 'Plot 20'),
         time_point = if_else(date == "2018-01-01", "Pre-bleaching", "Post-bleaching"),
         class_name = if_else(class_name == "Pocillopora", "Live", "Dead"))

# Create summary table of plot totals for live and dead coral area and convert areas to square meters
resilience_summary_reps <- resilience_plots %>% 
  group_by(time_point, class_name, plot) %>% 
  summarize(Surf_area = sum(surface_area),
            Plan_area = sum(planar_area)) %>% 
  mutate(Surf_area = Surf_area/10000,
         Plan_area = Plan_area/10000) 
  
resilience_summary_reps$time_point <- ordered(resilience_summary_reps$time_point, c("Pre-bleaching", "Post-bleaching"))

# Create summary table of average areas of live and dead coral by time point
resilience_summary <- resilience_summary_reps %>% 
  group_by(time_point, class_name) %>% 
  summarize(mean_SA = mean(Surf_area),
            SD_SA = sd(Surf_area),
            SE_SA = SD_SA/sqrt(5),
            mean_plan_area = mean(Plan_area),
            SD_plan_area = sd(Plan_area),
            SE_plan_area = SD_plan_area/sqrt(5))
  
resilience_summary$time_point <- ordered(resilience_summary$time_point, c("Pre-bleaching", "Post-bleaching"))
```

#### Plot totals using working area
```{r Figure 3: changes in colony number and live and dead surface areas}

## Fig 3a
# colony counts for pre-bleaching pie chart
colony_num_pre <- resilience_plots %>% 
  filter(time_point == "Pre-bleaching") %>% 
  count(class_name)

ggplot(colony_num_pre, aes(x = "", y = n, fill = class_name)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y") + 
  labs(fill = "Coral condition") +
  scale_fill_manual(values = c("#070604", "#969696")) +
  #scale_fill_manual(values = c("#969696", "#2C3B75")) +
  theme_void()

# colony counts for post-bleaching pie chart
colony_num_post <- resilience_plots %>% 
  filter(time_point == "Post-bleaching") %>% 
  count(class_name)

ggplot(colony_num_post, aes(x = "", y = n, fill = class_name)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y") + 
  labs(fill = "Coral condition") +
  scale_fill_manual(values = c("#070604", "#969696")) +
  #scale_fill_manual(values = c("#969696", "#2C3B75")) +
  theme_void()

## Fig 3b
# Graph of changes in total 3D surface areas of live and dead coral
ggplot(resilience_summary, aes(x = time_point, y = mean_SA)) +
  geom_line(aes(group = class_name),
            color = "black") +
  geom_point(data = resilience_summary_reps,
             aes(x = time_point,
                 y = Surf_area,
                 fill = class_name),
             color = "black",
             size = 2,
             shape = 21) +
   geom_errorbar(data = resilience_summary,
                aes(ymax = mean_SA + SE_SA,
                ymin = mean_SA - SE_SA),
                width = 0.1) +
  geom_point(aes(fill = class_name),
             color = "black",
             size = 5,
             shape = 24) +
  labs(x = "",
       y = "3D"~surface~area~(m^2),
       color = "Coral condition") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,35),
                     breaks = seq(0,35, by = 5)) +
  scale_fill_manual(values = c("#070604", "#969696")) +
  scale_color_manual(values = c("#070604", "#969696")) +
  #scale_fill_manual(values = c("#969696", "#2C3B75")) +
  #scale_color_manual(values = c("#969696", "#2C3B75")) +
  theme_classic()

```

#### Changes in colony size structure
```{r Figure 4: Changes in dead colony size classes}

## Size classes of live corals
# Compute quartiles of size classes for live corals before bleaching
live_quartiles <- resilience_plots %>% 
  filter(class_name == "Live")

live_quartiles <- live_quartiles$surface_area
quantile(live_quartiles)

# Create three size bins, where the 'medium' bin is a combination of the middle two quartiles
size_dist.small_large <- resilience_plots %>% 
  filter(class_name == "Live") %>% 
  mutate(size_class = case_when(surface_area > 400 ~ 'Large (> 400)',
                                surface_area > 100 ~ 'Medium (100-400)',
                                surface_area < 100 ~ 'Small (< 100)')) %>% 
  group_by(time_point, plot) %>% 
  count(size_class) 

# Calculate mean colony numbers for size classes and time points
size_summary <- size_dist.small_large %>% 
  group_by(time_point, size_class) %>% 
  summarize(mean_num = mean(n),
            SD_num = sd(n),
            SE_num = SD_num/sqrt(n()))

size_summary$time_point <- ordered(size_summary$time_point, c("Pre-bleaching", "Post-bleaching"))
size_summary$size_class <- ordered(size_summary$size_class, c("Small (< 100)", "Medium (100-400)","Large (> 400)"))

# Create column chart for different sized live colonies before and after bleaching
ggplot(size_summary, aes(x = size_class, y = mean_num, fill = time_point)) +
  geom_col(position = position_dodge()) +
  geom_errorbar(aes(ymax = mean_num + SE_num,
                    ymin = mean_num - SE_num),
                position = position_dodge(width = 0.9),
                width = 0) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = Size~class~(cm^2),
       y = "Number of colonies",
       fill = "Time point") +
  scale_fill_brewer(palette = "Paired") +
  theme_classic()

## Size classes of dead corals (using same three bin sizes as described above)
# Create dataframe for counts of dead colonies before and after bleaching using size bins created from live corals before bleaching
size_dist.dead <- resilience_plots %>% 
  filter(class_name == "Dead") %>% 
  mutate(size_class = case_when(surface_area > 400 ~ 'Large (> 400)',
                                surface_area > 100 ~ 'Medium (100-400)',
                                surface_area < 100 ~ 'Small (< 100)')) %>% 
  group_by(time_point, plot) %>% 
  count(size_class) 

size_summary_dead <- size_dist.dead %>% 
  group_by(time_point, size_class) %>% 
  summarize(mean_num = mean(n),
            SD_num = sd(n),
            SE_num = SD_num/sqrt(n()))


size_summary_dead$time_point <- ordered(size_summary_dead$time_point, c("Pre-bleaching", "Post-bleaching"))
size_summary_dead$size_class <- ordered(size_summary_dead$size_class, c("Small (< 100)", "Medium (100-400)","Large (> 400)"))

# Figure 4: column chart of different sized dead colonies before and after bleaching 
ggplot(size_summary_dead, aes(x = size_class, y = mean_num, fill = time_point)) +
  geom_col(position = position_dodge(),
           color = "black") +
  geom_errorbar(aes(ymax = mean_num + SE_num,
                    ymin = mean_num - SE_num),
                position = position_dodge(width = 0.9),
                width = 0.1) +
  scale_y_continuous(expand = c(0,0), limits = c(0,150)) +
  labs(x = Size~class~("3D"~surface~area~cm^2),
       y = "Number of dead colonies",
       fill = "") +
  #scale_fill_manual(values = c("#2F3D70", "#CABEE9")) +
  #scale_fill_manual(values = c("#6C90B9", "#DD3C51")) +
  scale_fill_manual(values = c("#115896", "#7ACCD7")) +
  theme_classic()

## Calculate max size for dead colonies to report in methods
dead_colonies_post <- resilience_plots %>% 
  filter(class_name == "Dead",
         time_point == "Post-bleaching")

max(dead_colonies_post$surface_area)
```

```{r Fig 5: 2D and 3D area comparison}

# Create dataframe for 2D (planar) and 3D (surface) areas for live corals only, before and after bleaching
area_comparison <- resilience_summary_reps %>% 
  pivot_longer(cols = Surf_area:Plan_area,
               names_to = "area_type",
               values_to = "area") %>% 
  mutate(time_point = case_when(time_point == "Pre-bleaching" ~ 2018,
                                TRUE ~ 2019),
         time_point = as.factor(time_point)) %>%
  filter(class_name == "Live") 

write.csv(area_comparison, "/Users/kaikopecky/Google Drive/Stier Lab/People/Kai Kopecky/Projects/Resilience plots bleaching/Coral bleaching photogrammetry_Remote Sensing\\area_comparison.csv")

# ANCOVA of area ~ area_type and time point
area_comparison_ancova <- aov(area ~ area_type*time_point, area_comparison) 
Anova(area_comparison_ancova, fit = "III")
TukeyHSD(area_comparison_ancova)

# Summary table of 3D and 2D areas before and after bleaching
area_comparison_summary <- area_comparison %>% 
  group_by(time_point, area_type) %>% 
  summarize(mean_area = mean(area),
            SE_area = sd(area)/sqrt(5))

# Plot of 3D and 2D areas before and after bleaching
ggplot(area_comparison_summary, aes(x = time_point, y = mean_area, shape = area_type)) +
  geom_errorbar(aes(ymax = mean_area + SE_area,
                ymin = mean_area - SE_area),
                width = 0.1,
                color = "black") +
  geom_line(aes(group = area_type),
            color = "black") +
  geom_point(aes(fill = time_point),
             size = 6) +
  scale_shape_manual(values = c(22, 24)) +
  labs(x = "Year",
       y = "3D"~surface~area~or~planar~area~(m^2),
       color = "") +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,30),
                     breaks = seq(0,30, by = 5)) +
  scale_fill_manual(values = c("#115896", "#7ACCD7")) +
  theme_classic()

```

```{r Comparison of colony numbers with automatic segmentation and manual improvement}

col_num_comparison <- read_csv("Data/Colony numbers_automatic vs manual.csv") %>% 
  clean_names() %>% 
  pivot_longer(cols = automatic:manual,
               names_to = "measurement_type",
               values_to = "number") %>% 
  group_by(year, class, measurement_type) %>% 
  summarize(total_col_num = sum(number))

```